Brewery.destroy_all
Brewery.create(name: 'Barbot', brewery_type: 'Brewpub', email: '', serves_people: true, foursquare_id: '51451975e4b0df0d731706e2')
Brewery.create(name: 'Bimba Brüder', brewery_type: 'Cervecería', email: 'info@bimbabruder.com', serves_people: true, foursquare_id: '')
Brewery.create(name: 'Buenas Costumbres', brewery_type: 'Cervecería', email: 'bcostumbresb@gmail.com', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Davok', brewery_type: 'Cervecería', email: 'info@davok.com.uy', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Dharma', brewery_type: 'Cervecería', email: 'cervezadharma@gmail.com', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Maragata', brewery_type: 'Cervecería', email: 'info@cervezamaragata.com.uy', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Volcánica', brewery_type: 'Cervecería', email: 'cervecería@volcanica.com.uy', serves_people: true, foursquare_id: '54e151b5498e2889d4cf1c99')
Brewery.create(name: 'Montevideo Brew House', brewery_type: 'Brewpub', email: 'info@mbh.com.uy', serves_people: true, foursquare_id: '526c77d9498e699e2fefd223')
Brewery.create(name: 'Cabesas Bier', brewery_type: 'Cervecería', email: 'contacto@cabesasbier.uy', serves_people: false, foursquare_id: '4ef540549adf60f83b757271')
Brewery.create(name: 'Cabesas Bier', brewery_type: 'Brewpub', email: 'contacto@cabesasbier.uy', serves_people: true, foursquare_id: '4ef540549adf60f83b757271')
Brewery.create(name: 'Pablo Bonnet', brewery_type: 'Cervecería', email: 'pbonnet@adinet.com.uy', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Ariscona', brewery_type: 'Cervecería', email: 'arisconacerveza@gmail.com', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Cien Doncellas', brewery_type: 'Brewpub', email: '', serves_people: true, foursquare_id: '')
Brewery.create(name: 'Chela Brandon', brewery_type: 'Cervecería', email: 'info@chelabrandon.com', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Cascada', brewery_type: 'Cervecería', email: 'cascada@cascada.com.uy', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Bizarra', brewery_type: 'Marca', email: 'hola@bizarra.uy', serves_people: false, foursquare_id: '')
Brewery.create(name: 'Tremenda', brewery_type: 'Marca', email: 'tremendaipa@gmail.com', serves_people: false, foursquare_id: '')

Venue.destroy_all
Venue.create(name: "Barbot", venue_type: "Brewpub", email: "", foursquare_id: "51451975e4b0df0d731706e2")
Venue.create(name: "Montevideo Brew House", venue_type: "Brewpub", email: "info@mbh.com.uy", foursquare_id: "526c77d9498e699e2fefd223")
Venue.create(name: "Cabesas Bier", venue_type: "Brewpub", email: "contacto@cabesasbier.uy", foursquare_id: "4ef540549adf60f83b757271")
Venue.create(name: "Cien Doncellas", venue_type: "Brewpub", email: "", foursquare_id: "")
Venue.create(name: "Hey Chopp", venue_type: "Bar", email: "", foursquare_id: "548b8d16498e13d74f2e87b5")
Venue.create(name: "Chopería Mastra", venue_type: "Bar", email: "choperíamam@mastra.com.uy", foursquare_id: "51d715d8498ea1854141e343")
Venue.create(name: "Chopería Mastra", venue_type: "Bar", email: "choperiapocitos@mastra.com.uy", foursquare_id: "533f4164498e92faaf52eef4")
Venue.create(name: "Chopería Mastra", venue_type: "Bar", email: "choperiapocitos@mastra.com.uy", foursquare_id: "54af172c498e215dcc1da489")
Venue.create(name: "Chopería Mastra", venue_type: "Bar", email: "choperiarivera@mastra.com.uy", foursquare_id: "55443a1f498eede8a2518396")
Venue.create(name: "Ennis XXX", venue_type: "Bar", email: "hola.ennis@gmail.com,ennis.pub@gmail.com", foursquare_id: "4fbb7549e4b007859e1a9c14")
Venue.create(name: "Ennis TN", venue_type: "Bar", email: "hola.ennis@gmail.com,ennis.pub@gmail.com", foursquare_id: "54029173498eeb96719f9baf")
Venue.create(name: "Shannon", venue_type: "Bar", email: "theshannon@theshannon.com.uy", foursquare_id: "4bbda8278ec3d13a26461c28")
Venue.create(name: "Burlesque", venue_type: "Bar", email: " info@burlesque.com.uy", foursquare_id: "4b5f946ff964a520cbc229e3")
Venue.create(name: "Gallagher's", venue_type: "Bar", email: "contacto@gallaghersmvd.com", foursquare_id: "50a83f8ae4b0f191c1746acd")
Venue.create(name: "Pacharán", venue_type: "Restaurant", email: "contacto@pacharan.com.uy", foursquare_id: "4d49df694509721e1db328b0")
Venue.create(name: "Los Horneros", venue_type: "Tienda", email: "somm.arossi@gmail.com", foursquare_id: "5558d572498e6c7f9e79005d")
Venue.create(name: "Los Querubines", venue_type: "Tienda", email: "contacto@losquerubines.uy", foursquare_id: "50fc7557011c47ca42eab88c")
Venue.create(name: "Shannon Store", venue_type: "Tienda", email: "contacto@shannonstore.com.uy", foursquare_id: "54342134498e709ee07b904e")
Venue.create(name: "Pepe Botella", venue_type: "Tienda", email: "", foursquare_id: "54fa3ec3498e7a3138fd2d48")
Venue.create(name: "Jacinto", venue_type: "Restaurant", email: "JACINTO@JACINTO.COM.UY", foursquare_id: "50783b84e4b0801687f52185")
Venue.create(name: "La Petite Cuisine", venue_type: "Restaurant", email: "", foursquare_id: "54b6a6ba498e241122aff5f1")
Venue.create(name: "Sin Pretensiones", venue_type: "Restaurant", email: "info@sinpretensiones.com.uy", foursquare_id: "5540fc4e498e22f511f8f17a")
Venue.create(name: "Tienda Inglesa MVD Shopping", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4bb27a2d4019a59399e336b8")
Venue.create(name: "Tienda Inglesa Portones", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4baa4d4bf964a520be5c3ae3")
Venue.create(name: "Tienda Inglesa Arocena", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4c06f42d0e0a2d7f5daeec0c")
Venue.create(name: "Tienda Inglesa Pocitos", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4bffae328d7a9c74826afa52")
Venue.create(name: "Tienda Inglesa Parque Posadas", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4d5fd8b8ef378cfaf22075a6")
Venue.create(name: "Tienda Inglesa Atlántida", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4b80699ef964a520f76f30e3")
Venue.create(name: "Tienda Inglesa Punta del Este", venue_type: "Tienda", email: " comentarios@tinglesa.com.uy", foursquare_id: "4b64c070f964a5204bcd2ae3")
Venue.create(name: "Kinko Bvar. España y Ellauri", venue_type: "Tienda", email: "info@kinko.com.uy", foursquare_id: "544d1286498eb6077fbc5ece")
Venue.create(name: "Kinko Arocena", venue_type: "Tienda", email: "info@kinko.com.uy", foursquare_id: "53e79aee498eaabb6e28066d")
Venue.create(name: "Kinko Palermo", venue_type: "Tienda", email: "info@kinko.com.uy", foursquare_id: "53b71a3d498eef48c839f123")
Venue.create(name: "Kinko Soca", venue_type: "Tienda", email: "info@kinko.com.uy", foursquare_id: "53a2d1df498ea4f0852a8dba")
Venue.create(name: "Kinko Bustamante", venue_type: "Tienda", email: "info@kinko.com.uy", foursquare_id: "542cfb7e498e111fdf4797f1")
Venue.create(name: "Iberpark Soriano", venue_type: "Tienda", email: "soriano@iberpark.com.uy", foursquare_id: "4e5c334fb99329e22ae3cdeb")
Venue.create(name: "Iberpark Tres Cruces", venue_type: "Tienda", email: "trescruces@iberpark.com.uy", foursquare_id: "503bf572e4b0bbcb18032b02")
Venue.create(name: "Iberpark centro", venue_type: "Tienda", email: "tango@iberpark.com.uy", foursquare_id: "4e3c655c8877b00cfc393213")
Venue.create(name: "Iberpark Universidad", venue_type: "Tienda", email: "acevedo@iberpark.com.uy", foursquare_id: "4ee3d71929c220f97128cbbd")
Venue.create(name: "Iberpark Costa Urbana", venue_type: "Tienda", email: "costaurbana@iberpark.com.uy", foursquare_id: "4f69163ee4b0fa6f4cb3c6ac")
Venue.create(name: "Iberpark Mercado Agrícola", venue_type: "Tienda", email: "mam@iberpark.com.uy", foursquare_id: "51223192e4b05d422fb721f3")
Venue.create(name: "Iberpark Portones", venue_type: "Tienda", email: "portones@iberpark.com.uy", foursquare_id: "536e85f9498ef5316d989048")
Venue.create(name: "Kfé", venue_type: "Bar", email: "-", foursquare_id: "519ba004498ec9f2570cdfe1")
Venue.create(name: "Las Vizcarras", venue_type: "Tienda", email: "lasvizcarras@lasvizcarras.com", foursquare_id: "519ba004498ec9f2570cdfe1")
Venue.create(name: "St. Patrick's", venue_type: "Bar", email: "", foursquare_id: "528ad0f711d22e71077e2847")
Venue.create(name: "Brickell", venue_type: "Bar", email: "info@brickell.uy", foursquare_id: "541debfb498edc8f8be3aa38")
Venue.create(name: "Lalá", venue_type: "Bar", email: "lalacafe2014@gmail.com", foursquare_id: "542337b9498e9d95c6cd0f93")
Venue.create(name: "La Molienda Ciudad Vieja", venue_type: "Tienda", email: "info@lamolienda.com.uy", foursquare_id: "50ad20b7e4b013861149f781")
Venue.create(name: "La Molienda Ejido", venue_type: "Tienda", email: "info@lamolienda.com.uy", foursquare_id: "")
Venue.create(name: "Tío Jack", venue_type: "Bar", email: "", foursquare_id: "51f5c6ad498e8b4fc7710a38")


Beer.destroy_all
Beer.create(brand: "Bizarra", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Bizarra").first.try(:id))
Beer.create(brand: "Bizarra", style: "IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Bizarra").first.try(:id))
Beer.create(brand: "Cabesas Bier", style: "Brown Porter", color: "Negra", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Cabesas Bier", style: "Pilsen Lager", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Cabesas Bier", style: "Scottish Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Cabesas Bier", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Sabotaje", style: "Oatmeal Stout", color: "Negra", alcohol: "Alto", bitterness: "Medio", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Atómica", style: "IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Bárbara", style: "Witbier", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Cabutiña", style: "Pumpkin Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Cabesas Bier").first.try(:id))
Beer.create(brand: "Davok", style: "EPA", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Davok").first.try(:id))
Beer.create(brand: "Davok", style: "Sweet Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Davok").first.try(:id))
Beer.create(brand: "Davok", style: "IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Davok").first.try(:id))
Beer.create(brand: "Davok", style: "Barley Wine", color: "Rubia", alcohol: "Muy alto", bitterness: "Muy alto", size: "330 cc", draft: false, brewery_id: Brewery.where(name: "Davok").first.try(:id))
Beer.create(brand: "Davok", style: "Irish Red", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Davok").first.try(:id))
Beer.create(brand: "Volcánica", style: "Belgian Blonde Ale", color: "Rubia", alcohol: "Alto", bitterness: "Medio", size: "500 cc", draft: true, brewery_id: Brewery.where(name: "Volcánica").first.try(:id))
Beer.create(brand: "Volcánica", style: "Dubbel", color: "Roja", alcohol: "Alto", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Volcánica").first.try(:id))
Beer.create(brand: "Volcánica", style: "Belgian IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Volcánica").first.try(:id))
Beer.create(brand: "Volcánica", style: "Belgian Strong Dark", color: "Negra", alcohol: "Muy alto", bitterness: "Muy alto", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Volcánica").first.try(:id))
Beer.create(brand: "Volcánica", style: "Belgian Strong", color: "Rubia", alcohol: "Alto", bitterness: "Medio", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Volcánica").first.try(:id))
Beer.create(brand: "Mastra", style: "Belgian Blonde Ale", color: "Rubia", alcohol: "Alto", bitterness: "Bajo", size: "330 cc", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "Golden Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "330 cc", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "Scottish Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "330 cc", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "American Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "330 cc", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "Witbier", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "Strong Golden Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "IPA", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Mastra", style: "Amber Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Mastra").first.try(:id))
Beer.create(brand: "Bimba Brüder", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Bimba Brüder").first.try(:id))
Beer.create(brand: "Bimba Brüder", style: "Scottish Ale", color: "Roja", alcohol: "Bajo", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Bimba Brüder").first.try(:id))
Beer.create(brand: "Bimba Brüder", style: "Witbier", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Bimba Brüder").first.try(:id))
Beer.create(brand: "Bimba Brüder", style: "Oatmeal Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Bimba Brüder").first.try(:id))
Beer.create(brand: "Coffee Stout", style: "Oatmeal Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Dharma").first.try(:id))
Beer.create(brand: "Golden Ale", style: "Golden Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Dharma").first.try(:id))
Beer.create(brand: "Pale Ale", style: "Pale Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Dharma").first.try(:id))
Beer.create(brand: "Chela Brandon", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Chela Brandon").first.try(:id))
Beer.create(brand: "Chela Brandon", style: "Honey Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Chela Brandon").first.try(:id))
Beer.create(brand: "Chela Brandon", style: "Porter", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Chela Brandon").first.try(:id))
Beer.create(brand: "Pale Ale Rubia", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Buenas Costumbres").first.try(:id))
Beer.create(brand: "Pale Ale Roja", style: "Irish Red", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Buenas Costumbres").first.try(:id))
Beer.create(brand: "Pale Ale Negra", style: "Porter", color: "Negra", alcohol: "Medio", bitterness: "Bajo", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Buenas Costumbres").first.try(:id))
Beer.create(brand: "Pale Ale IPA", style: "IPA", color: "Rubia", alcohol: "alto", bitterness: "Medio", size: "500 cc", draft: false, brewery_id: Brewery.where(name: "Buenas Costumbres").first.try(:id))
Beer.create(brand: "Tremenda IPA", style: "IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Tremenda").first.try(:id))
Beer.create(brand: "Maragata", style: "Pilsen Lager", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Maragata").first.try(:id))
Beer.create(brand: "Maragata", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Maragata").first.try(:id))
Beer.create(brand: "PB", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Pablo Bonnet").first.try(:id))
Beer.create(brand: "PB", style: "IPA", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Pablo Bonnet").first.try(:id))
Beer.create(brand: "PB", style: "Irish Red", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "Pablo Bonnet").first.try(:id))
Beer.create(brand: "Ariscona", style: "sin id", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Ariscona").first.try(:id))
Beer.create(brand: "Ariscona", style: "sin id", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Ariscona").first.try(:id))
Beer.create(brand: "Cien doncellas rubias", style: "Cream Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Cien Doncellas").first.try(:id))
Beer.create(brand: "Cien doncellas castañas", style: "Blonde Ale", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Cien Doncellas").first.try(:id))
Beer.create(brand: "Cien doncellas coloradas", style: "Scottish Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Cien Doncellas").first.try(:id))
Beer.create(brand: "Cien doncellas dulces", style: "Honey Ale", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "660 cc", draft: true, brewery_id: Brewery.where(name: "Cien Doncellas").first.try(:id))
Beer.create(brand: "MBH", style: "Dry Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "MBH", style: "Brown Ale", color: "Negra", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "MBH", style: "IPA", color: "Rubia", alcohol: "Alto", bitterness: "Muy alto", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "MBH", style: "Belgian Strong", color: "Roja", alcohol: "Alto", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "MBH", style: "Scottish Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "MBH", style: "Kölsch", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Montevideo Brew House").first.try(:id))
Beer.create(brand: "Pionera", style: "Porter", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "O'Neill").first.try(:id))
Beer.create(brand: "Patora", style: "Scottish Ale", color: "Roja", alcohol: "Medio", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "O'Neill").first.try(:id))
Beer.create(brand: "Dorada Esteña", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "O'Neill").first.try(:id))
Beer.create(brand: "Luna de Miel", style: "Honey Ale", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "O'Neill").first.try(:id))
Beer.create(brand: "León de Aiguá", style: "Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "León de Aiguá").first.try(:id))
Beer.create(brand: "León de Aiguá", style: "Porter", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "660 cc", draft: false, brewery_id: Brewery.where(name: "León de Aiguá").first.try(:id))
Beer.create(brand: "Bremen", style: "Pilsen Lager", color: "Rubia", alcohol: "Bajo", bitterness: "Bajo", size: "1000 cc", draft: false, brewery_id: Brewery.where(name: "Cascada").first.try(:id))
Beer.create(brand: "Burton Bitter", style: "EPA", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Belgian Blond", style: "Belgian Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "De Lobo Porter", style: "Porter", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Honey Beer", style: "Honey Ale", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Marilyn Golden", style: "Golden Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Monastere Belgian Blond", style: "Belgian Blonde Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Mumbai IPA", style: "IPA", color: "Rubia", alcohol: "Medio", bitterness: "Alto", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Old Strong Ale", style: "Strong Ale", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Sacramento Kölsch", style: "Kölsch", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Stout", style: "Stout", color: "Negra", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Thames Pale Ale", style: "EPA", color: "Rubia", alcohol: "Medio", bitterness: "Medio", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
Beer.create(brand: "Weizen", style: "Weizen", color: "Rubia", alcohol: "Medio", bitterness: "Bajo", size: "chopp", draft: true, brewery_id: Brewery.where(name: "Barbot").first.try(:id))
